name: MLSecOps Pipeline

on:
  workflow_dispatch:
push:

jobs:

  mlsecops:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - uses: sigstore/cosign-installer@v3

    - name: Install Tools
      run: |
        pip install modelscan==0.8.2
        pip install semgrep
        pip install pyyaml
        pip install cyclonedx-python-lib

    - name: ModelScan
      run: |
        modelscan -p models/evil.pkl
      continue-on-error: true

    - name: Verify Signature
      run: |
        bash scripts/verify_model.sh

    - name: Generate MLBOM
      run: |
        python scripts/generate_mlbom.py
        
    - name: Display MLBOM
      run: |
        cat mlbom/mlbom-cyclonedx.json
        
    - name: Upload MLBOM
      uses: actions/upload-artifact@v4
      with:
        name: cyclonedx-mlbom
        path: mlbom/mlbom-cyclonedx.json
        
    - name: MCP Security Scan
      run: |
        semgrep scan \
          --config semgrep/mcp-rules.yml \
          dvmcp/dvmcp/challenges/
      continue-on-error: true

    - name: Governance Check
      run: |
        python scripts/governance_check.py
      continue-on-error: true
